language: php
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - phpenv config-rm xdebug.ini || true
  # Add the oauth token to prevent GitHub timeouts.
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer self-update
  - composer --version
  - composer global require "hirak/prestissimo:^0.3"
  - composer global require "squizlabs/php_codesniffer:2.*"
  - composer global require "drupal/coder:8.2.*"
  - phpcs --config-set installed_paths $HOME/.composer/vendor/drupal/coder/coder_sniffer

install:
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the Biiir code base.
  - phing build -Dversion=$VERSION -Dbranch=$TRAVIS_COMMIT

before_script:
  - cd docroot
  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done
  - phantomjs --webdriver=4444 > /dev/null &
  - sleep 5

script:
  - cd ./profiles/biiir
  - behat --strict

matrix:
  fast_finish: true
